package com.example.freitassantiagojuanexamen3tAdultos.ui.navegacion

sealed class Screens(val route: String){
    object MenuScreen: Screens("Pantalla inicial")

    object Ejercicio1: Screens("Ejercicio 1")
    object Ejercicio2: Screens("Ejercicio 2")
    object Ejercicio3: Screens("Ejercicio 3")
    object Ejercicio4: Screens("Ejercicio 4")
    object Ejercicio5: Screens("Ejercicio 5")
    object Ejercicio6: Screens("Ejercicio 6")
    object Ejercicio7: Screens("Ejercicio 7")
    object Ejercicio8: Screens("Ejercicio 8")
    object Ejercicio9: Screens("Ejercicio 9")
    object Ejercicio10: Screens("Ejercicio 10")
    object Ejercicio11: Screens("Ejercicio 11")
    object Ejercicio12: Screens("Ejercicio 12")
    object Ejercicio13: Screens("Ejercicio 13")
    object Ejercicio14: Screens("Ejercicio 14")
    object Ejercicio15: Screens("Ejercicio 15")
    object Ejercicio16: Screens("Ejercicio 16")
    object Ejercicio17: Screens("Ejercicio 17")
    object Ejercicio18: Screens("Ejercicio 18")
    object Ejercicio19: Screens("Ejercicio 19")
    object Ejercicio20: Screens("Ejercicio 20")
    object Ejercicio21: Screens("Ejercicio 21")
    object Ejercicio22: Screens("Ejercicio 22")
    object Ejercicio23: Screens("Ejercicio 23")
    object Ejercicio24: Screens("Ejercicio 24")
    object Ejercicio25: Screens("Ejercicio 25")
    object Ejercicio26: Screens("Ejercicio 26")
    object Ejercicio27: Screens("Ejercicio 27")
    object Ejercicio28: Screens("Ejercicio 28")
    object Ejercicio29: Screens("Ejercicio 29")
    object Ejercicio30: Screens("Ejercicio 30")
    object Ejercicio31: Screens("Ejercicio 31")
    object Ejercicio32: Screens("Ejercicio 32")
    object Ejercicio33: Screens("Ejercicio 33")
    object Ejercicio34: Screens("Ejercicio 34")
    object Ejercicio35: Screens("Ejercicio 35")
    object Ejercicio36: Screens("Ejercicio 36")
    object Ejercicio37: Screens("Ejercicio 37")
    object Ejercicio38: Screens("Ejercicio 38")
    object Ejercicio39: Screens("Ejercicio 39")
    object Ejercicio40: Screens("Ejercicio 40")

}
